---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-jul17-test5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-jul17-test5 
  name: test-jul17-test5
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi